<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ChangeLog</string>
		<string>CHANGELOG</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>GNU ChangeLog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.date.changelog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.author.changelog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.email.changelog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\d\d\d\d-\d\d-\d\d)\s([\w|\s]+)\s&lt;(.*)&gt;$\n?</string>
			<key>name</key>
			<string>markup.heading.changelog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.changelog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.path.changelog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.changelog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.changelog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\*)\s(.*)\s\((.*)\)\:(.*$\n?)</string>
			<key>name</key>
			<string>markup.list.unnumbered.changelog</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.vermarker.changelog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.version.changelog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.changelog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(--) ([0-9]+\.[0-9]+\.[0-9]+) -- tagged as (\w*)\.$\n?</string>
			<key>name</key>
			<string>meta.vermarker.changelog</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.changelog</string>
	<key>uuid</key>
	<string>D489089C-AFA2-4350-AD69-10064AB92BB9</string>
</dict>
</plist>
